package:
  name: starry
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script_env:
    - CC
    - CXX

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - pybind11

  run:
    - python
    - vs2015_runtime  # [win]

test:
  imports:
    - python_example

about:
  summary: Analytic occultation light curves.
  license_file: LICENSE
